### ISSUE TITLE
extends path not supported ?

### ISSUE THREAD

**Issue by chipbite** [gerry-rohling/structurizr-parser#3]
Hi! Very cool projects, just played with this one for a few minutes, tested on a simple DSL that extends and found that it seems to cause a hiccup...

```
// space-c4.dsl -- C4 DSL workspace for Ipex Space
workspace extends ../ipex-base-c4ws.dsl {
    name "space-sketching" 
    description "drafting"

    model {

    }

    views {

    }
}

```

Errors show that it is surprised by the extends ../[adasda] statement.
Seems like the path is making it upset.

```
  console.log
    2-19: unexpected character: ->.<- at offset: 69, skipped 3 characters.

      at tests/C4Interpreter.test.ts:27:21
          at Array.forEach (<anonymous>)

  console.log
    2-23: unexpected character: ->-<- at offset: 76, skipped 1 characters.

      at tests/C4Interpreter.test.ts:27:21
          at Array.forEach (<anonymous>)

  console.log
    2-27: unexpected character: ->-<- at offset: 81, skipped 1 characters.

      at tests/C4Interpreter.test.ts:27:21
          at Array.forEach (<anonymous>)
```

Anyway, thought I might tell you about it :-)

Take care!

**Comment by gerry-rohling** [comment]
Thanks for the feedback. I have updated the tokenizer and parser and I think this is now fixed.

**Comment by mawid6** [comment]
Very nice! I will most definitely have a look and get back to you.

**Comment by chipbite** [comment]
Yup, passed my silly simple testdata. Nice that you got back on this, thanks.

Do you aim to integrate this into the vs code extension you started?
